[AppKit] Don't add NSTextInput.DoCommandBySelector in .NET.
It's deprecated (since macOS 10.6), so just don't add it to avoid any conflicts with other API.

Fixes:

> build/dotnet/macos/generated-sources/AppKit/NSTextView.g.cs(6455,37): error CS0102: The type 'NSTextView' already contains a definition for 'DoCommandBySelector'