[AppKit] Don't bind the NSTextList constructor with NSTextListMarkerFormats for .NET.
There's already a constructor with a NSTextListMarkerFormats, which wraps the
generic string version, so that should work well enough (this way also makes
it possible for app developers to pass in unknown string values).

Fixes:

> build/dotnet/macos/generated-sources/AppKit/NSTextList.g.cs(138,10): error CS0111: Type 'NSTextList' already defines a member called 'NSTextList' with the same parameter types