[AppKit] Remove NSTextView.ChangeColor in .NET, it's provided by a protocol now.
Fixes:

> build/dotnet/macos/generated-sources/AppKit/NSTextView.g.cs(46,187): error CS0535: 'NSTextView' does not implement interface member 'INSColorChanging.ChangeColor(NSColorPanel?)'