[ObjCRuntime] Add a non-deprecated internal system-version checking API and use it in a few places.
The PlatformHelper class is deprecated, so implement a new version that isn't
deprecated, and which shares a common API between all platforms.

For macOS we can now use NSProcessInfo.ProcessInfo.OperatingSystemVersion to
determine the OS version, because it's supported in all versions of macOS we
support for .NET.

Fixes:

> CoreMedia/CMSync.cs(590,11): error CS0103: The name 'PlatformHelper' does not exist in the current context