[xharness] Capture writes to stdout so that it can be re-read later.
Fixes a confusing crash that occurred when trying to diagnose an error
condition:

    error MT1221: Could not find the paired iPhone simulator for the WatchOS simulator 'watchOS 3.0 (14S326) - Apple Watch - 38mm'.
    Test run failed

    Unhandled Exception:
    System.AggregateException: One or more errors occurred. ---> System.NotSupportedException: Specified method is not supported.
      at xharness.Log.GetReader () [0x00001] in /Users/builder/data/lanes/3426/8aa61bd1/source/xamarin-macios/tests/xharness/Log.cs:28
      at xharness.AppRunner+<RunAsync>c__async0.MoveNext () [0x0098c] in /Users/builder/data/lanes/3426/8aa61bd1/source/xamarin-macios/tests/xharness/AppRunner.cs:438
      --- End of inner exception stack trace ---
      at System.Threading.Tasks.Task.ThrowIfExceptional (Boolean includeTaskCanceledExceptions) [0x00014] in /private/tmp/source-mono-4.4.0/bockbuild-mono-4.4.0-branch/profiles/mono-mac-xamarin/build-root/mono-x86/external/referencesource/mscorlib/system/threading/Tasks/Task.cs:2157
      at System.Threading.Tasks.Task`1[TResult].GetResultCore (Boolean waitCompletionNotification) [0x00034] in /private/tmp/source-mono-4.4.0/bockbuild-mono-4.4.0-branch/profiles/mono-mac-xamarin/build-root/mono-x86/external/referencesource/mscorlib/system/threading/Tasks/Future.cs:562
      at System.Threading.Tasks.Task`1[TResult].get_Result () [0x00000] in /private/tmp/source-mono-4.4.0/bockbuild-mono-4.4.0-branch/profiles/mono-mac-xamarin/build-root/mono-x86/external/referencesource/mscorlib/system/threading/Tasks/Future.cs:532
      at xharness.Harness.Run () [0x0005f] in /Users/builder/data/lanes/3426/8aa61bd1/source/xamarin-macios/tests/xharness/Harness.cs:439
      at xharness.Harness.Execute () [0x00032] in /Users/builder/data/lanes/3426/8aa61bd1/source/xamarin-macios/tests/xharness/Harness.cs:500
      at xharness.MainClass.Main (System.String[] args) [0x002b9] in /Users/builder/data/lanes/3426/8aa61bd1/source/xamarin-macios/tests/xharness/Program.cs:63
    ---> (Inner Exception #0) System.NotSupportedException: Specified method is not supported.
      at xharness.Log.GetReader () [0x00001] in /Users/builder/data/lanes/3426/8aa61bd1/source/xamarin-macios/tests/xharness/Log.cs:28
      at xharness.AppRunner+<RunAsync>c__async0.MoveNext () [0x0098c] in /Users/builder/data/lanes/3426/8aa61bd1/source/xamarin-macios/tests/xharness/AppRunner.cs:438 <---

The problem here is the MT1221 error, the posterior exception is something
else that goes wrong later, when xharness tries to read what was written to
stdout to try and get more information about the failure.

The fix is to capture anything written to ConsoleLog, so that the output can
be processed later.