[MediaPlayer] Force MPMusicPlayerController.NowPlayingItem to return an MPMediaItem. Fixes #9578.
iOS might return an instance of MPMusicPlayerMediaItemProxy, which is a
subclass of NSProxy, and when we try to look up the corresponding managed
class we end up with:

    ObjCRuntime.RuntimeException: Can't lookup the Objective-C class 0x203d98438 (_MPMusicPlayerMediaItemProxy) when the dynamic registrar has been linked away.
      at ObjCRuntime.Class.LookupClass (System.IntPtr klass, System.Boolean throw_on_error) [0x00086] in [...]/xamarin-macios/src/ObjCRuntime/Class.cs:231
      at ObjCRuntime.Class.Lookup (System.IntPtr klass) [0x00000] in [...]/xamarin-macios/src/ObjCRuntime/Class.cs:202
      at ObjCRuntime.Runtime.GetNSObject[T] (System.IntPtr ptr) [0x0003b] in <9da7682f030546d88255d9aa760d3afa>:0
      at MediaPlayer.MPMusicPlayerController.get_NowPlayingItem () [0x00003] in [...]/xamarin-macios/src/build/ios/native/MediaPlayer/MPMusicPlayerController.g.cs:459
      at MusicPlayer.ViewController.RefreshButtonOnTouchUpInside (System.Object sender, System.EventArgs e) [0x0003d] in /Users/rolf/Downloads/MusicPlayer/MusicPlayer/ViewController.cs:32

and that's no good. So force the managed type to be MPMediaItem.

Fixes https://github.com/xamarin/xamarin-macios/issues/9578.