[generator] Don't use culture-aware API.
Currently fails with:

/Library/Frameworks/Mono.framework/Versions/6.12.0/lib/mono/msbuild/15.0/bin/MSBuild.dll /nologo /bl:build/common/bgen.exe.binlog /m /p:Features=strict /p:Configuration=Debug /p:IntermediateOutputPath=build/IDE/obj/common/ /p:OutputPath=build/common /restore /verbosity:quiet generator.csproj
/Users/rolf/work/maccore/dotnet/xamarin-macios/src/generator.cs(1381,62): error CS1501: No overload for method 'Replace' takes 3 arguments [/Users/rolf/work/maccore/dotnet/xamarin-macios/src/generator.csproj]
/Users/rolf/work/maccore/dotnet/xamarin-macios/src/generator.cs(1602,32): error CS1501: No overload for method 'Replace' takes 3 arguments [/Users/rolf/work/maccore/dotnet/xamarin-macios/src/generator.csproj]
/Users/rolf/work/maccore/dotnet/xamarin-macios/tools/common/TargetFramework.cs(201,44): error CS1501: No overload for method 'GetHashCode' takes 1 arguments [/Users/rolf/work/maccore/dotnet/xamarin-macios/src/generator.csproj]
/Users/rolf/work/maccore/dotnet/xamarin-macios/tools/common/TargetFramework.cs(205,21): error CS1501: No overload for method 'GetHashCode' takes 1 arguments [/Users/rolf/work/maccore/dotnet/xamarin-macios/src/generator.csproj]
/Users/rolf/work/maccore/dotnet/xamarin-macios/src/btouch.cs(638,120): error CS1501: No overload for method 'Replace' takes 3 arguments [/Users/rolf/work/maccore/dotnet/xamarin-macios/src/generator.csproj]
/Users/rolf/work/maccore/dotnet/xamarin-macios/src/generator.cs(2866,54): error CS1501: No overload for method 'Replace' takes 3 arguments [/Users/rolf/work/maccore/dotnet/xamarin-macios/src/generator.csproj]
/Users/rolf/work/maccore/dotnet/xamarin-macios/src/generator.cs(2923,33): error CS1503: Argument 2: cannot convert from 'System.StringComparison' to 'int' [/Users/rolf/work/maccore/dotnet/xamarin-macios/src/generator.csproj]
/Users/rolf/work/maccore/dotnet/xamarin-macios/src/generator.cs(3128,69): error CS1503: Argument 2: cannot convert from 'System.StringComparison' to 'int' [/Users/rolf/work/maccore/dotnet/xamarin-macios/src/generator.csproj]
/Users/rolf/work/maccore/dotnet/xamarin-macios/src/generator.cs(3916,21): error CS1501: No overload for method 'Contains' takes 2 arguments [/Users/rolf/work/maccore/dotnet/xamarin-macios/src/generator.csproj]
/Users/rolf/work/maccore/dotnet/xamarin-macios/src/generator.cs(4006,38): error CS1503: Argument 2: cannot convert from 'System.StringComparison' to 'int' [/Users/rolf/work/maccore/dotnet/xamarin-macios/src/generator.csproj]
/Users/rolf/work/maccore/dotnet/xamarin-macios/src/generator.cs(5702,40): error CS1501: No overload for method 'Replace' takes 3 arguments [/Users/rolf/work/maccore/dotnet/xamarin-macios/src/generator.csproj]
/Users/rolf/work/maccore/dotnet/xamarin-macios/src/generator.cs(6045,59): error CS1503: Argument 2: cannot convert from 'System.StringComparison' to 'int' [/Users/rolf/work/maccore/dotnet/xamarin-macios/src/generator.csproj]
/Users/rolf/work/maccore/dotnet/xamarin-macios/src/generator.cs(6763,22): error CS1501: No overload for method 'Contains' takes 2 arguments [/Users/rolf/work/maccore/dotnet/xamarin-macios/src/generator.csproj]
/Users/rolf/work/maccore/dotnet/xamarin-macios/src/generator.cs(6764,34): error CS1501: No overload for method 'Replace' takes 3 arguments [/Users/rolf/work/maccore/dotnet/xamarin-macios/src/generator.csproj]
/Users/rolf/work/maccore/dotnet/xamarin-macios/src/generator.cs(6966,34): error CS1501: No overload for method 'Contains' takes 2 arguments [/Users/rolf/work/maccore/dotnet/xamarin-macios/src/generator.csproj]
/Users/rolf/work/maccore/dotnet/xamarin-macios/src/generator.cs(7018,71): error CS1503: Argument 2: cannot convert from 'System.StringComparison' to 'int' [/Users/rolf/work/maccore/dotnet/xamarin-macios/src/generator.csproj]
/Users/rolf/work/maccore/dotnet/xamarin-macios/src/generator.cs(8590,18): error CS1501: No overload for method 'Replace' takes 3 arguments [/Users/rolf/work/maccore/dotnet/xamarin-macios/src/generator.csproj]
/Users/rolf/work/maccore/dotnet/xamarin-macios/src/generator-enums.cs(172,34): error CS1501: No overload for method 'Replace' takes 3 arguments [/Users/rolf/work/maccore/dotnet/xamarin-macios/src/generator.csproj]
gmake: *** [Makefile.generator:14: build/common/bgen.exe] Error 1