[UIKit] Fix implementation of UIImagePickerController.[ImagePicker|Navigation]ControllerDelegate for .NET.
* Use a protocolized version of the
  UIImagePickerController.[ImagePicker|Navigation]ControllerDelegate
  properties for .NET.
* Fix this compilation error:
        UIKit/UIImagePickerController.cs(35,16): error CS0266: Cannot implicitly convert type 'UIKit.IUIImagePickerControllerDelegate' to 'Foundation.NSObject'. An explicit conversion exists (are you missing a cast?)
        UIKit/UIImagePickerController.cs(44,16): error CS0266: Cannot implicitly convert type 'UIKit.IUINavigationControllerDelegate' to 'Foundation.NSObject'. An explicit conversion exists (are you missing a cast?)