[AVFoundation] Define a few types in api definition for non-macOS platforms.
Fixes:

> avfoundation.cs(4846,3): error CS0246: The type or namespace name 'AVSampleCursorSyncInfo' could not be found (are you missing a using directive or an assembly reference?)
> avfoundation.cs(4849,3): error CS0246: The type or namespace name 'AVSampleCursorSyncInfo' could not be found (are you missing a using directive or an assembly reference?)
> avfoundation.cs(4860,3): error CS0246: The type or namespace name 'AVSampleCursorStorageRange' could not be found (are you missing a using directive or an assembly reference?)
> avfoundation.cs(4863,3): error CS0246: The type or namespace name 'AVSampleCursorChunkInfo' could not be found (are you missing a using directive or an assembly reference?)
> avfoundation.cs(4869,3): error CS0246: The type or namespace name 'AVSampleCursorStorageRange' could not be found (are you missing a using directive or an assembly reference?)

because these types only exists in macOS.